### ISSUE TITLE
Support for angular 5

### ISSUE THREAD

**Issue by gsiradze** [scttcper/ngx-color#245]
"@angular/core": "^5.2.11",
    "ngx-color": "^4.1.0",

I'm getting an error

> webpack: Compiled successfully.
> ERROR in src/app/...module.ts(6,35): error TS2307: Cannot find module 'ngx-color/sketch'.

When I ctrl-click on `ColorSketchModule` It actually navigates inside `node_modules`, so It's properly installed.
I also tried deleting `node_modules` and installing from  scratch.

Also it works OK with     `"@angular/core": "~8.2.13",` (have created demo project for that)

**Comment by scttcper** [comment]
v2.0.7 was the last version to support angular 5
